# Generated by Django 5.2.6 on 2025-09-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_appointment_age_appointment_concern_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='age',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='concern',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_gender',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='gender',
        ),
    ]
