# Generated by Django 5.2.6 on 2025-09-20 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_remove_appointment_time_appointment_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
    ]
